kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven
  volumes:
    - name: cache
      path: /root/.m2
  commands:
    - mvn clean install -DskipTests

volumes:
  - name: cache # The name use in this pipeline,
    host:
      path: /var/lib/cache # The path be used in the host.
